import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAssetsStore } from '../store';
import { listUsers } from '@/features/users/api';
import type { CreateAssetDto } from '../types';
import type { User } from '@/features/users/types';
import { formatDate } from '@/lib/dateFormatter';
import QRCodeGenerator from '@/components/QRCodeGenerator';
import { QrCode } from 'lucide-react';
import toast from 'react-hot-toast';

export default function AssetDetailsPage() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const isEditMode = id && id !== 'new';

  const { currentAsset, isLoading, error, fetchAssetById, createAsset, updateAsset } = useAssetsStore();

  const [users, setUsers] = useState<User[]>([]);
  const [loadingUsers, setLoadingUsers] = useState(true);
  const [showQRCode, setShowQRCode] = useState(false);

  const [formData, setFormData] = useState<CreateAssetDto>({
    asset_code: '',
    name: '',
    serial_number: '',
    remote_id: '',
    asset_type: '',
    condition: '',
    status: 'available',
    assigned_to: '',
    scanned_by: '',
    scan_datetime: '',
    description: '',
    ownership: '',
    office_location: '',
    extension: '',
    deskphones: '',
    mouse: '',
    keyboard: '',
    department: '',
    notes: '',
    ownerId: '',
    // asset_code will be auto-generated by backend
  });

  // Redirect non-admin users
  useEffect(() => {
    const userStr = localStorage.getItem('user');
    if (userStr) {
      const user = JSON.parse(userStr);
      if (user.role !== 'ADMIN') {
        navigate('/my-assets');
      }
    }
  }, [navigate]);

  // Fetch users on mount
  useEffect(() => {
    const fetchUsersData = async () => {
      try {
        const usersData = await listUsers();
        setUsers(usersData);
      } catch (err) {
        console.error('Failed to fetch users:', err);
      } finally {
        setLoadingUsers(false);
      }
    };
    fetchUsersData();
  }, []);

  useEffect(() => {
    if (isEditMode && id) {
      fetchAssetById(id);
    }
  }, [id, isEditMode, fetchAssetById]);

  useEffect(() => {
    if (currentAsset && isEditMode) {
      setFormData({
        asset_code: currentAsset.asset_code || '',
        name: currentAsset.name || '',
        serial_number: currentAsset.serial_number || '',
        remote_id: currentAsset.remote_id || '',
        asset_type: currentAsset.asset_type || '',
        condition: currentAsset.condition || '',
        status: currentAsset.status || 'available',
        assigned_to: currentAsset.assigned_to || '',
        scanned_by: currentAsset.scanned_by || '',
        scan_datetime: currentAsset.scan_datetime || '',
        description: currentAsset.description || '',
        ownership: currentAsset.ownership || '',
        office_location: currentAsset.office_location || '',
        extension: currentAsset.extension || '',
        deskphones: currentAsset.deskphones || '',
        mouse: currentAsset.mouse || '',
        keyboard: currentAsset.keyboard || '',
        department: currentAsset.department || '',
        notes: currentAsset.notes || '',
        ownerId: (currentAsset as any).ownerId || '',
      });
    }
  }, [currentAsset, isEditMode]);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value } = e.target;

    // If changing the owner, also update assigned_to with user's email and status
    if (name === 'ownerId') {
      const selectedUser = users.find(u => u.id === value);
      setFormData((prev) => ({
        ...prev,
        ownerId: value,
        assigned_to: selectedUser ? selectedUser.email : '',
        status: value ? 'assigned' : 'available', // Auto-update status
      }));
    } else {
      setFormData((prev) => ({
        ...prev,
        [name]: value,
      }));
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      if (isEditMode && id) {
        await updateAsset(id, formData);
        toast.success('Asset updated successfully');
      } else {
        await createAsset(formData);
        toast.success('Asset created successfully');
      }
      navigate('/assets');
    } catch (err) {
      console.error('Failed to save asset:', err);
      toast.error(isEditMode ? 'Failed to update asset' : 'Failed to create asset');
    }
  };

  if (isLoading && isEditMode) {
    return <div className="p-8">Loading asset...</div>;
  }

  return (
    <div className="p-8 max-w-4xl mx-auto">
      <div className="mb-6">
        <button
          onClick={() => navigate('/assets')}
          className="text-blue-600 hover:text-blue-700 mb-4 flex items-center gap-2"
        >
          ← Back to Assets
        </button>
        <h1 className="text-3xl font-bold dark:text-white">
          {isEditMode ? 'Edit Asset' : 'Create New Asset'}
        </h1>
      </div>

      {error && (
        <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg text-red-600">
          {error}
        </div>
      )}

      <form onSubmit={handleSubmit} className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Asset Code - Only show when editing (read-only) */}
          {isEditMode && (
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                Asset Code (Auto-generated)
              </label>
              <input
                type="text"
                name="asset_code"
                value={formData.asset_code}
                disabled
                className="w-full px-4 py-2 border border-gray-300 rounded-lg bg-gray-100 text-gray-600 cursor-not-allowed"
                placeholder="Will be auto-generated"
              />
              <p className="mt-1 text-xs text-gray-500">
                Asset codes are automatically generated and cannot be changed
              </p>
            </div>
          )}

          {/* Name */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Asset Name <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              name="name"
              value={formData.name}
              onChange={handleChange}
              required
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="e.g., Dell Laptop"
            />
          </div>

          {/* Serial Number */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Serial Number
            </label>
            <input
              type="text"
              name="serial_number"
              value={formData.serial_number}
              onChange={handleChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="e.g., SN123456789"
            />
          </div>

          {/* Remote ID */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Remote ID
            </label>
            <input
              type="text"
              name="remote_id"
              value={formData.remote_id}
              onChange={handleChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="e.g., RMT-001"
            />
          </div>

          {/* Asset Type */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Asset Type
            </label>
            <input
              type="text"
              name="asset_type"
              value={formData.asset_type}
              onChange={handleChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="e.g., Laptop, Desktop, Monitor"
            />
          </div>

          {/* Condition */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Condition
            </label>
            <select
              name="condition"
              value={formData.condition}
              onChange={handleChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select condition</option>
              <option value="Excellent">Excellent</option>
              <option value="Good">Good</option>
              <option value="Fair">Fair</option>
              <option value="Poor">Poor</option>
            </select>
          </div>

          {/* Status */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Status
            </label>
            <select
              name="status"
              value={formData.status}
              onChange={handleChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="available">Available</option>
              <option value="assigned">Assigned</option>
              <option value="maintenance">Maintenance</option>
              <option value="repair">Repair</option>
              <option value="retired">Retired</option>
            </select>
          </div>

          {/* Assigned To */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Assigned To (User)
            </label>
            <select
              name="ownerId"
              value={formData.ownerId}
              onChange={handleChange}
              disabled={loadingUsers}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            >
              <option value="">Select a user (optional)</option>
              {users.map((user) => (
                <option key={user.id} value={user.id}>
                  {user.email} {user.name ? `(${user.name})` : ''}
                </option>
              ))}
            </select>
            <p className="mt-1 text-xs text-gray-500">
              Select the user who will be assigned this asset
            </p>
          </div>

          {/* Department */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Department
            </label>
            <input
              type="text"
              name="department"
              value={formData.department}
              onChange={handleChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="e.g., IT, HR, Finance"
            />
          </div>

          {/* Office Location */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Office Location
            </label>
            <input
              type="text"
              name="office_location"
              value={formData.office_location}
              onChange={handleChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="e.g., Building A, Floor 3"
            />
          </div>

          {/* Ownership */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Ownership
            </label>
            <input
              type="text"
              name="ownership"
              value={formData.ownership}
              onChange={handleChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="e.g., Company, Leased"
            />
          </div>

          {/* Extension */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Extension
            </label>
            <input
              type="text"
              name="extension"
              value={formData.extension}
              onChange={handleChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Phone extension"
            />
          </div>

          {/* Desk Phones */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Desk Phones
            </label>
            <input
              type="text"
              name="deskphones"
              value={formData.deskphones}
              onChange={handleChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Phone numbers"
            />
          </div>

          {/* Mouse */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Mouse
            </label>
            <input
              type="text"
              name="mouse"
              value={formData.mouse}
              onChange={handleChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Mouse type/model"
            />
          </div>

          {/* Keyboard */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Keyboard
            </label>
            <input
              type="text"
              name="keyboard"
              value={formData.keyboard}
              onChange={handleChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Keyboard type/model"
            />
          </div>

          {/* Scanned By */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Scanned By
            </label>
            <input
              type="text"
              name="scanned_by"
              value={formData.scanned_by}
              onChange={handleChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Scanner name"
            />
          </div>

          {/* Scan DateTime */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Scan Date/Time
            </label>
            <input
              type="text"
              name="scan_datetime"
              value={formData.scan_datetime}
              onChange={handleChange}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Scan date and time"
            />
          </div>

          {/* Description - Full Width */}
          <div className="md:col-span-2">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Description
            </label>
            <textarea
              name="description"
              value={formData.description}
              onChange={handleChange}
              rows={3}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Asset description..."
            />
          </div>

          {/* Notes - Full Width */}
          <div className="md:col-span-2">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Notes
            </label>
            <textarea
              name="notes"
              value={formData.notes}
              onChange={handleChange}
              rows={3}
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              placeholder="Additional notes..."
            />
          </div>
        </div>

        {/* Form Actions */}
        <div className="mt-8 flex gap-4 justify-end">
          {isEditMode && currentAsset && (
            <button
              type="button"
              onClick={() => setShowQRCode(true)}
              className="px-6 py-2 bg-purple-600 dark:bg-purple-500 text-white rounded-lg hover:bg-purple-700 dark:hover:bg-purple-600 flex items-center gap-2 transition-colors"
            >
              <QrCode className="w-4 h-4" />
              <span>Generate QR Code</span>
            </button>
          )}
          <button
            type="button"
            onClick={() => navigate('/assets')}
            className="px-6 py-2 border border-gray-300 dark:border-gray-600 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-700 dark:text-gray-300 transition-colors"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={isLoading}
            className="px-6 py-2 bg-blue-600 dark:bg-blue-500 text-white rounded-lg hover:bg-blue-700 dark:hover:bg-blue-600 disabled:bg-gray-400 transition-colors flex items-center gap-2"
          >
            {isLoading ? (
              <>
                <div className="flex items-center gap-1">
                  <div className="w-2 h-2 bg-white rounded-full animate-bounce" style={{ animationDelay: '0ms' }}></div>
                  <div className="w-2 h-2 bg-white rounded-full animate-bounce" style={{ animationDelay: '150ms' }}></div>
                  <div className="w-2 h-2 bg-white rounded-full animate-bounce" style={{ animationDelay: '300ms' }}></div>
                </div>
                <span className="sr-only">Saving</span>
              </>
            ) : (
              isEditMode ? 'Update Asset' : 'Create Asset'
            )}
          </button>
        </div>
      </form>

      {/* QR Code Modal */}
      {isEditMode && currentAsset && (
        <QRCodeGenerator
          isOpen={showQRCode}
          onClose={() => setShowQRCode(false)}
          assetCode={currentAsset.asset_code || ''}
          assetName={currentAsset.name || ''}
          assetId={currentAsset.id || ''}
        />
      )}

      {/* Related Tickets Section - Only show in edit mode */}
      {isEditMode && currentAsset && (currentAsset as any).tickets && (
        <div className="mt-8 bg-white dark:bg-gray-800 rounded-lg shadow p-6">
          <h2 className="text-xl font-bold mb-4 dark:text-white">Related Tickets ({(currentAsset as any).tickets?.length || 0})</h2>
          {(currentAsset as any).tickets?.length === 0 ? (
            <p className="text-gray-500 dark:text-gray-400 text-center py-8">No tickets associated with this asset</p>
          ) : (
            <div className="table-container">
              <table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700">
                <thead className="bg-gray-50 dark:bg-gray-700">
                  <tr>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">Ticket #</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">Title</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">Status</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">Priority</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">Created</th>
                    <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">Actions</th>
                  </tr>
                </thead>
                <tbody className="bg-white dark:bg-gray-800 divide-y divide-gray-200 dark:divide-gray-700">
                  {(currentAsset as any).tickets?.map((ticket: any) => (
                    <tr key={ticket.id} className="hover:bg-gray-50 dark:hover:bg-gray-700">
                      <td className="px-4 py-3 whitespace-nowrap text-sm font-medium text-blue-600 dark:text-blue-400">
                        {ticket.number || ticket.id}
                      </td>
                      <td className="px-4 py-3 text-sm text-gray-900 dark:text-white">{ticket.title}</td>
                      <td className="px-4 py-3 whitespace-nowrap">
                        <span className={`px-2 py-1 text-xs font-semibold rounded-full ${
                          ticket.status === 'closed' ? 'bg-gray-100 text-gray-800' :
                          ticket.status === 'in_progress' ? 'bg-blue-100 text-blue-800' :
                          'bg-green-100 text-green-800'
                        }`}>
                          {ticket.status}
                        </span>
                      </td>
                      <td className="px-4 py-3 whitespace-nowrap">
                        <span className={`px-2 py-1 text-xs font-semibold rounded-full ${
                          ticket.priority === 'critical' ? 'bg-red-100 text-red-800' :
                          ticket.priority === 'high' ? 'bg-orange-100 text-orange-800' :
                          ticket.priority === 'medium' ? 'bg-yellow-100 text-yellow-800' :
                          'bg-gray-100 text-gray-800'
                        }`}>
                          {ticket.priority}
                        </span>
                      </td>
                      <td className="px-4 py-3 whitespace-nowrap text-sm text-gray-500 dark:text-gray-400">
                        {formatDate(ticket.createdAt)}
                      </td>
                      <td className="px-4 py-3 whitespace-nowrap text-sm">
                        <button
                          onClick={() => navigate(`/tickets/${ticket.id}`)}
                          className="text-blue-600 hover:text-blue-800 font-medium"
                        >
                          View
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}
    </div>
  );
}